name: 新功能请求
description: 提出你想要的功能。
labels: ['enhancement']
assignees: ADJazzzz

body:
    - type: markdown
      attributes:
          value: |
              # 欢迎
              请确保你所提出的功能脚本的确没有。

    - id: describe
      type: textarea
      validations:
          required: true
      attributes:
          label: '描述'
          description: |
              请清晰而简明地描述你想要的功能。
